ROCmSoftwarePlatform/composable_kernel

library/src/tensor_operation_instance/gpu/batched_gemm/CMakeLists.txt
library/src/tensor_operation_instance/gpu/batched_gemm/device_batched_gemm_xdl_bf16_bf16_bf16_gkm_gkn_gmn_instance.cpp
library/src/tensor_operation_instance/gpu/batched_gemm/device_batched_gemm_xdl_bf16_bf16_bf16_gkm_gnk_gmn_instance.cpp
library/src/tensor_operation_instance/gpu/batched_gemm/device_batched_gemm_xdl_bf16_bf16_bf16_gmk_gkn_gmn_instance.cpp
library/src/tensor_operation_instance/gpu/batched_gemm/device_batched_gemm_xdl_bf16_bf16_bf16_gmk_gnk_gmn_instance.cpp
library/src/tensor_operation_instance/gpu/gemm_bias2d/device_gemm_xdl_c_shuffle_bias_2d_f16_f16_f16_mk_kn_mn_instance.cpp
profiler/include/profile_batched_gemm_impl.hpp
profiler/src/profile_batched_gemm.cpp

Batched gemm bf16

---

test/gemm/gemm_bf16.cpp
test/gemm/gemm_fp16.cpp
test/gemm/gemm_fp32.cpp
test/gemm/gemm_int8.cpp
test/include/test_util.hpp

Gemm test return value

---

test/batched_gemm/batched_gemm_fp16.cpp
test/space_filling_curve/space_filling_curve.cpp

test/batched_gemm_fp16 return 0 if it passes test; otherwise return 1.

ctest of batched_gemm returns 0 or 1

---

include/ck/tensor_operation/gpu/device/device_gemm.hpp
include/ck/tensor_operation/gpu/device/tensor_layout.hpp
library/include/ck/library/host_tensor/host_tensor_generator.hpp
profiler/include/profile_batched_gemm_impl.hpp
test/batched_gemm/batched_gemm_fp16.cpp

batched_gemm: use profiler in ctest

---

example/17_convnd_bwd_data_xdl/convnd_bwd_data_xdl.cpp
include/ck/tensor_operation/gpu/device/device_convnd_bwd_data_xdl_ndhwc_kzyxc_ndhwk.hpp
library/include/ck/library/reference_tensor_operation/cpu/reference_conv_bwd_data.hpp
profiler/include/profile_convnd_bwd_data_impl.hpp

@j4yan pls check out if all comments are resolved

Patch for bwd data comments

---

include/ck/tensor_operation/gpu/block/blockwise_gemm_xdlops.hpp

- Removed unnecessary lds loads

Fixed LDS loads in Blockwise XDL Gemm

---

include/ck/tensor_operation/gpu/device/device_batched_gemm_xdl.hpp
include/ck/tensor_operation/gpu/device/device_conv3d_fwd_xdl_ndhwc_kzyxc_ndhwk.hpp

Add documentation to batched_gemm. Also renamed `ComputeBasePtr` to `ComputePtrOffset`.

add comments to batched_gemm

---

CMakeLists.txt
example/CMakeLists.txt
include/ck/options.hpp
include/ck/options.hpp.in

not using cmake to do code gen

No cmake code gen

---

example/20_convnd_bwd_weight_xdl/convnd_bwd_weight_xdl.cpp
include/ck/tensor_operation/gpu/device/device_base.hpp
include/ck/tensor_operation/gpu/device/device_convnd_backward_weight_xdl_c_shuffle_nhwc_kyxc_nhwk.hpp

Add GetWorkSpaceSize to base arg and make an example on convnd_bwd_we…ight

add GetWorkSpaceSize to base arg

---

Jenkinsfile
script/parse_perf_data.py
script/run_performance_tests.sh

A bunch of small but important changes:
Adding a switch in jenkins to use the default or custom docker image.
Adding performance tests on MI200 during CI.
Adding the number of Compute Units to the tables.
Adding the script that can be launched from anywhere and post the results to database and grafana boards.

Add performance tests on MI200 in CI, reporting number of CUs, add stand-alone perf test.

---

include/ck/tensor_operation/gpu/device/device_convnd_backward_weight_xdl_c_shuffle_nhwc_kyxc_nhwk.hpp

use universal workspace pointer in bwd-weight

[bug fix]use universal workspace pointer in bwd-weight

---

client_example/01_gemm/gemm.cpp

Fix a typo in gemm client example.

minor fix in gemm client example

---

include/ck/tensor_operation/gpu/grid/gridwise_softmax.hpp

Let's see if this change fixes sporadic validation failure for standalone softmax. The issue may be race condition around blockwise reductions which reads and writes LDS in unsafe manner.

Fix sporadic standalone softmax validation failure

---

Jenkinsfile

This should give us a better chance of QA runs completing successfully.

restart the stages on MI200 in case of failures

---

script/profile_splitK_gemm.sh
script/run_full_performance_tests.sh

- Add a script for splitK_gemm
- Add tests into run_full_performance_tests
- Disabled splitK_gemm fp32 due to failures

add splitK_gemm performance tests

---

include/ck/utility/transpose_vectors.hpp

Evaluating workaround for potential hazard in some compiler generated instruction sequences [SWDEV-354439](https://ontrack-internal.amd.com/browse/SWDEV-354439)
This fix allows us to use larger tile size without validation errors.

Use intrinsic instead of inline asm for in-register transpose

---

Jenkinsfile

This should resolve the compiler error in the Client App stage.

use rocm5.2 compiler as default, use same flags for amd-stg-open as for release.

---

include/ck/tensor_operation/gpu/device/device_batched_contraction_multiple_d_xdl_cshuffle.hpp

- Replace G offset calc in batched_contraction with long_index

fixed G offset calc in batched_contraction for large tensor

---

Dockerfile
Jenkinsfile

Main changes in this PR:
1. Added ROCM version as another parameter and set the default value to 5.3.
2. Set the default compiler version to the rocm5.3 compiler.
3. Decoupled ccache setup from MIOpen and activated it.
4. Cleaned up some obsolete code in jenkins file.

Allow setting ROCM version, activate cchache, etc.

---

Jenkinsfile

Two small changes:
1. Fix for the issue that caused crashes on some of the CI nodes that didn't have recent docker images.
2. Added daily test runs for develop branch with the latest version of the amd-stg-open compiler branch (at noon Pacific time).

Fix build issue and schedule daily tests with latest staging compiler version.

---

client_example/10_elementwise_normalization/CMakeLists.txt
client_example/10_elementwise_normalization/elementwise_layernorm2d.cpp
include/ck/tensor_operation/gpu/grid/gridwise_elementwise_layernorm_welford_variance.hpp
library/include/ck/library/reference_tensor_operation/cpu/reference_layernorm.hpp

Added client example for elementwise_normalization, for Pytorch use.

add client example for elementwise_normalization

---

include/ck/tensor_operation/gpu/device/impl/device_grouped_conv_bwd_weight_gnwc_gkxc_gnwk_xdl_cshuffle.hpp

This PR aims to resolve all the compilation errors which were introduced since #498

Fix more build errors on CI server

---

include/ck/tensor_operation/gpu/device/device_base.hpp
include/ck/tensor_operation/gpu/device/device_permute.hpp
include/ck/utility/math_v2.hpp

This PR is a quick fix to solve the issue mentioned by  [Issue 1926](https://github.com/ROCmSoftwarePlatform/MIOpen/issues/1926).

Remove including of cmath

---

library/include/ck/library/utility/host_tensor.hpp

This fix takes care of all test and example failures with DEBUG build. 
All CI tests are passing fine.

fix a bug for 6-dim kernels

---

include/ck/tensor_operation/gpu/grid/gridwise_sparse_embeddings_forward_layernorm.hpp

remove unused variable

---

Jenkinsfile
include/ck/tensor_operation/gpu/device/impl/device_batched_gemm_softmax_gemm_permute_xdl_cshuffle.hpp

This change will fix a bug for gfx1030 target and will start building for  gfx1030 target during CI.

fix a bug when building for gfx1030 target.

---

docs/Doxyfile
docs/source/API_Reference_Guide.rst
docs/source/conf.py
docs/source/refs.bib
include/ck/tensor_operation/gpu/block/blockwise_gemm_xdlops.hpp
include/ck/tensor_operation/gpu/block/blockwise_softmax.hpp
include/ck/tensor_operation/gpu/block/thread_group_tensor_slice_transfer_v4r1.hpp
include/ck/tensor_operation/gpu/grid/gridwise_batched_gemm_softmax_gemm_xdl_cshuffle_v1.hpp
include/ck/tensor_operation/gpu/thread/threadwise_tensor_slice_transfer.hpp
library/include/ck/library/utility/device_memory.hpp

* Modify Doxygen config to pick up include directories recursively
* Add DeviceMem struct to API Reference guide
* Add classes that are used in Flash Attention kernel

Generate output using Doxygen / Breathe

---

include/ck/tensor_operation/gpu/block/blockwise_softmax.hpp

Quick fix to unblock the team. We may refine the descriptions later.

Add descriptions to avoid build issues

---

Jenkinsfile
cmake/EnableCompilerWarnings.cmake
include/ck/tensor_operation/gpu/device/impl/device_gemm_multiple_d_wmma_cshuffle.hpp
include/ck/tensor_operation/gpu/device/impl/device_gemm_wmma.hpp
include/ck/tensor_operation/gpu/grid/gridwise_gemm_multiple_d_wmma_cshuffle.hpp
include/ck/utility/amd_inline_asm.hpp
include/ck/utility/amd_wmma.hpp

1. Change Gridwise Gemm+MultipleD blockwise GEMM to naive one
2. Follow up AIT side verification problem,  Detect PyTorch + gfx1100 sanity issue
3. Fix RRR Gemm sanity
4. Isolate wmma instructions #621

[Navi3x] Multiple issue fix

---

include/ck/utility/amd_wmma.hpp

Urgency bug, it broke all WMMA operations.
Report in #634

[Navi3x]Fix arch limitation bug

---

include/ck/utility/data_type.hpp

reduce fp32->bf16 cbranch in asm, idea by @asroy.

rtn in ternary way
