- host/driver_offline/CMakeLists.txt
- host/driver_offline/include/device_gemm_xdlops_km_kn_mn.hpp
- host/driver_offline/include/device_gemm_xdlops_km_nk_mn.hpp
- host/driver_offline/include/device_gemm_xdlops_mk_kn_mn.hpp
- host/driver_offline/include/device_gemm_xdlops_mk_nk_mn.hpp
- host/driver_offline/src/gemm_driver_offline.cpp
- host/host_tensor/include/gemm_common.hpp
- host/host_tensor/include/host_gemm.hpp
- script/run.sh
Add GEMM driver and GEMM kernel for
TT: A[m, k] * B [k, n] = C[m, n]
TN: A[m, k] * B [n, k] = C[m, n]
NT: A[k, m] * B [k, n] = C[m, n]
NN: A[k, m] * B [n, k] = C[m, n]
MI-100 fp16, unlocked frequency (initialized with random integer value)
> GEMM driver and kernel

- composable_kernel/include/tensor_operation/gridwise_gemm_xdlops_v2r3.hpp
- host/driver_offline/include/device_convolution_forward_implicit_gemm_v4r4r4_xdlops_nhwc_kyxc_nhwk.hpp
- host/driver_offline/include/driver_gemm_xdlops_v2r3.hpp
In GridwiseGemm_k0mk1_k0nk1_mn_xdlops_v2r3, sometimes there is no main K0 loop. So you need to detect that on host, and not using main K0 loop in the kernel.
GridwiseGemm_bk0mk1_bk0nk1_mn_xdlops_v2r4 has same issue, and need to be fixed in separate PR
> [Bug fix] GridwiseGemm_k0mk1_k0nk1_mn_xdlops_v2r3 k0 main loop

- composable_kernel/include/tensor_operation/blockwise_gemm_xdlops.hpp
- composable_kernel/include/tensor_operation/threadwise_tensor_slice_transfer.hpp
* BlockwiseGemmXdlops_k0mk1_k0nk1_m0n0m1n1m2m3m4n2_v1::MakeCGridDescriptor_M0_N0_M1_N1_M2_M3_M4_N2()
* ThreadwiseTensorSliceTransfer_v1r3 logic for calculating "forward_sweep"
> Manually apply bug fix changes in pr #63

- device_operation/include/device_gemm_shuffle_xdl.hpp
- device_operation/include/device_gemm_xdl_c_shuffle.hpp
- example/1_gemm_xdl/gemm_xdl.cpp
- script/clang-format-overwrite.sh
[What]
1. Add DeviceGemmShuffleXdl
2. Revise example of gemm_xdl
[Why] Prepare to add shuuffle version of D = alpha * (A * B) + beta * C
[How] Imitate DeviceGemmXdl and device_conv2d_fwd_xdl_c_shuffle_nhwc_kyxc_nhwk.hpp
> Add gemm_shuffle host api

- include/ck/tensor_operation/gpu/thread/threadwise_tensor_slice_transfer.hpp
- include/ck/tensor_operation/gpu/thread/threadwise_tensor_slice_transfer_v6r1.hpp
- include/ck/tensor_operation/gpu/thread/threadwise_tensor_slice_transfer_v6r2.hpp
- include/ck/tensor_operation/gpu/thread/threadwise_tensor_slice_transfer_v6r3.hpp
- test/space_filling_curve/space_filling_curve.cpp
Added case `SpaceFillingCurve::GetNumAccess()=0` in `GetCoordinateResetStep` didn't deal with the case where `SpaceFillingCurve::GetNumAccess()=0`, which caused the reversion https://github.com/ROCmSoftwarePlatform/composable_kernel/pull/111
This PR should resolve the issue.
> Use Space Filling Curve in Threadwise Copy

- include/ck/tensor_operation/gpu/device/device_conv2d_bwd_data_xdl_nhwc_kyxc_nhwk.hpp
- library/include/ck/library/tensor_operation_instance/gpu/reduce/device_reduce_instance_blockwise_i8_i32_i8.hpp
- library/src/tensor_operation_instance/gpu/gemm/device_gemm_xdl_c_shuffle_bf16_bf16_bf16_km_kn_mn_instance.cpp
- library/src/tensor_operation_instance/gpu/gemm/device_gemm_xdl_c_shuffle_bf16_bf16_bf16_km_nk_mn_instance.cpp
- library/src/tensor_operation_instance/gpu/gemm/device_gemm_xdl_c_shuffle_bf16_bf16_bf16_mk_kn_mn_instance.cpp
- library/src/tensor_operation_instance/gpu/gemm/device_gemm_xdl_splitk_f16_f16_f16_mk_nk_mn_instance.cpp
- profiler/src/profiler.cpp
- test/gemm/gemm_bf16.cpp
- test/gemm/gemm_int8.cpp
- test/include/test_util.hpp
Many Operations were turned off in previous PR #126
> Re-enable op disabled in ckProfiler by mistake previously

- example/12_reduce/reduce_blockwise.cpp
- library/include/ck/library/host_tensor/host_reduction.hpp
- library/include/ck/library/host_tensor/host_tensor.hpp
- library/src/obselete_driver_offline/conv_add_fwd_driver_offline_nchwc.cpp
- library/src/obselete_driver_offline/conv_bwd_driver_offline.cpp
- library/src/obselete_driver_offline/conv_fwd_driver_offline.cpp
- library/src/obselete_driver_offline/conv_fwd_driver_offline_nchwc.cpp
- library/src/obselete_driver_offline/conv_maxpool_fwd_driver_offline_nchwc.cpp
- library/src/obselete_driver_offline/conv_wrw_driver_offline.cpp
- library/src/obselete_driver_offline/gemm_driver_offline.cpp
- profiler/include/profile_batched_gemm_impl.hpp
- profiler/include/profile_gemm_bias_2d_impl.hpp
- profiler/include/profile_gemm_bias_relu_impl.hpp
- profiler/include/profile_gemm_impl.hpp
- profiler/include/profile_gemm_reduce_impl.hpp
- profiler/include/profile_grouped_gemm_impl.hpp
- profiler/include/profile_reduce_impl.hpp
- test/gemm_split_k/gemm_split_k.cpp
- test/reduce/reduce_no_index.cpp
- test/reduce/reduce_with_index.cpp
Several EPYC nodes I have access to experience massive slowdown using multi-threaded tensor initialization. Reverting to single-threaded and see if it improves CI time.
CI reports total test time of single vs multithreaded tensor initial value generator: 512.33 sec vs 1025.49 sec. So it's definitely cutting down the test time.
CI test log using single-threaded tensor initialization  (http://micimaster.amd.com/blue/organizations/jenkins/MLLibs%2Fcomposable_kernel/detail/single-thd-tensor-init/1/pipeline/156/)
```
[2022-03-30T12:01:56.733Z] Test project /var/jenkins/workspace/le_kernel_single-thd-tensor-init/build/test
[2022-03-30T12:01:56.733Z]       Start  1: test_magic_number_division
[2022-03-30T12:01:56.733Z]       Start  2: test_space_filling_curve
[2022-03-30T12:01:56.733Z] …
```
> Test: Use single thread for tensor init

- include/ck/tensor_operation/gpu/device/device_batched_gemm_xdl.hpp
Fixed memory access issue https://github.com/ROCmSoftwarePlatform/composable_kernel/issues/164.
The issue was caused by using number of rows as the stride (leading dimension) of column-major matrices when creating grid descriptors.
> fixed issue164

- profiler/include/profile_batched_gemm_impl.hpp
- profiler/src/profile_batched_gemm.cpp
For some data types and matrix layouts, `BatchCount` was not passed into `bool profile_batched_gemm_impl()`.
> Fix typo in batched gemm profiler

- example/12_reduce/reduce_blockwise.cpp
- include/ck/utility/math_v2.hpp
- include/ck/utility/reduction_common.hpp
- library/include/ck/library/host_tensor/host_reduce_util.hpp
- library/include/ck/library/host_tensor/host_reduction.hpp
- profiler/include/profile_reduce_impl.hpp
- test/reduce/reduce_no_index.cpp
- test/reduce/reduce_with_index.cpp
This P.R is to remove the using of half_float::half in Host Reduction so that ck::half_t is used by Reduction on both the kernel and host.  Some host math functions are added to support ck::half on host.
> Use ck::half_t for Host Reduction

- include/ck/tensor_operation/gpu/thread/threadwise_tensor_slice_transfer_v3r1.hpp
- include/ck/utility/transpose_vectors.hpp
Mitigation to INT8 kernel slowdown due to early memory `waitcnt vmcnt(0)` with interwave optimization enabled.
Using inline asm appears to avoid some early `waitcnt vmcnt()`
> Use inline asm for 4x4 int8 transposition

- script/clang-format-overwrite.sh
Changing clang-format script to format only modified files visible in `git status` command.
> Clang-format only modified files.

- include/ck/config.hpp
- include/ck/tensor_operation/gpu/block/blockwise_gemm_xdlops.hpp
- include/ck/tensor_operation/gpu/device/device_batched_gemm_reduce_xdl_cshuffle.hpp
- include/ck/tensor_operation/gpu/device/device_gemm_reduce_xdl_cshuffle.hpp
- include/ck/tensor_operation/gpu/device/device_gemm_xdl_cshuffle.hpp
- include/ck/tensor_operation/gpu/grid/gridwise_gemm_pipeline_v1.hpp
- include/ck/tensor_operation/gpu/grid/gridwise_gemm_reduce_xdl_cshuffle_v1.hpp
- include/ck/tensor_operation/gpu/grid/gridwise_gemm_xdl_cshuffle_v1.hpp
- include/ck/tensor_operation/gpu/warp/xdlops_gemm.hpp
To avoid register spills seen on latest hipclang, getting best perf requires patches yet to be upstreamed + internal LLVM based off Mainline #9110 as listed here:
http://gerrit-git.amd.com/plugins/gitiles/lightning/ec/llvm-project/+/refs/heads/aukerbow/9110-ck
There is known verification in some `DeviceGemmXdl` kernels that have register spills. `DeviceGemmXdlCShuffle` kernels passed verifications.
List of kernels failed verification due to suspected register spill, using `./ckProfiler gemm`. A lot of false positives from BF16 verification failure is due to rounding errors
Update (5/5/2022): The latest commit 56790a62c avoids validation failure by rolling out interwave scheduling to C-shuffle gemm variants only.
<details><summary> Detail </summary>
<p>
test fp32 TT
test fp32 TN
test fp32 …
> Manual control of MAC cluster for improved interwave performance

- example/09_convnd_fwd/convnd_fwd_xdl_fp16.cpp
- example/09_convnd_fwd/convnd_fwd_xdl_fp32.cpp
- example/09_convnd_fwd/convnd_fwd_xdl_int8.cpp
- example/17_convnd_bwd_data_xdl/convnd_bwd_data_xdl.cpp
- example/20_convnd_bwd_weight_xdl/convnd_bwd_weight_xdl.cpp
- include/ck/tensor_operation/gpu/device/device_conv2d_fwd_xdl_c_shuffle_nhwc_kyxc_nhwk.hpp
- include/ck/tensor_operation/gpu/device/device_convnd_fwd_xdl_nhwc_kyxc_nhwk.hpp
- include/ck/tensor_operation/gpu/grid/gridwise_gemm_xdlops_v3r1.hpp
This PR fix following bug:
using changes in commit ```aff78f8``` + develop (or ```a054f7d604d3bfee9e4ad410df15397bc354ae3d```)
using change in commit ```aff78f8```+ ```070619fbf17cf12a99ac91690335d1ed2efeefb3```
There seems to be a bug introduced into conv kernel by PR #235, perf is also lower
> Fixing conv bug 

- include/ck/tensor_operation/gpu/device/device_convnd_backward_weight_xdl_c_shuffle_nhwc_kyxc_nhwk.hpp
fix #291 
1. simplify ```has_main_k0_block_loop ``` logic by using lambda.
2. rename ``` TypeConvertFunctor ``` by ```TypeConvertFp32ToBf16Functor```
3. fix a tensor transform bug in 3d conv.
> fix Issue 291

- example/04_gemm_add_add_fastgelu/run_gemm_add_add_fastgelu_example.inc
- library/include/ck/library/utility/literals.hpp
The compiler complains about global user-defined literals `""_uz` & `""_zu`, thus I move them into namespace `ck::literals` to prevent the error message.  
The `ck::literals` namespace follows the design of standard literals (under `std::literals` namespace).
> Move literal ""_uz & ""_zu into namespace 'ck::literals'

- example/12_reduce/CMakeLists.txt
- example/12_reduce/README.md
- example/12_reduce/reduce_blockwise.cpp
- example/12_reduce/reduce_blockwise_impl.hpp
- example/12_reduce/reduce_example_common.hpp
- example/12_reduce/reduce_multiblock_atomic_add.cpp
- example/12_reduce/reduce_multiblock_atomic_add_impl.hpp
Update to Reduction examples, so that 
1) Various data types (fp16/fp32/bp16/int8/fp64) are tested 
2) Various input tensor shapes and reducing dimensions are tested 
3) Both Blockwise and Multiblock (split-k) are tested
The int4 type is not added at present.
> Add examples  for reduction fp16/fp32/bp16/int8/fp64   for  3d/4d/5d 

- include/ck/tensor_operation/gpu/block/blockwise_gemm_xdlops.hpp
- include/ck/tensor_operation/gpu/grid/gridwise_batched_gemm_gemm_xdl_cshuffle_v1.hpp
- include/ck/tensor_operation/gpu/grid/gridwise_batched_gemm_softmax_gemm_xdl_cshuffle_v1.hpp
- include/ck/tensor_operation/gpu/warp/xdlops_gemm.hpp
- try to avoid LDS data hazard in `gemm_softmax_gemm` as seen in sporadic CI failures reported by @asroy 
(http://micimaster.amd.com/blue/organizations/jenkins/MLLibs%2Fcomposable_kernel/detail/fused-gemm/9/pipeline)
- `gemm_gemm` and `gemm_softmax_gemm`: reclaim Gemm0 AB block space when processing Gemm1; allows larger B1 tile size
- address a few oversights and bugs; closes #359 (thanks feedback from @danyao12)
> Hotfix LDS data hazard in fused attention

- example/16_gemm_multi_d_multi_reduces/CMakeLists.txt
- example/16_gemm_multi_d_multi_reduces/gemm_max_xdl_fp16.cpp
- include/ck/tensor_operation/gpu/grid/gridwise_gemm_multiple_d_multiple_r_xdl_cshuffle.hpp
Fix issue of https://github.com/ROCmSoftwarePlatform/composable_kernel/issues/358
[Solution]
We need to sync lds even in first loop because Gemm also use the same LDS.
> Fix bug of CI fail for gemm_reduce_max

- CMakeLists.txt
- Jenkinsfile
This change will enable building CK with clang, using any version of compiler (e.g., 5.1.0 release, ck-9110 (default), or amd-stg-open). There will be a new build parameter "BUILD_COMPILER" set to "hipcc" by default. When set to "clang" or any other value, it will use clang.
> Add an option to build CK with clang directly

- example/32_batched_gemm_scale_softmax_gemm/batched_gemm_scale_softmax_gemm_permute_xdl_fp16.cpp
- include/ck/tensor_operation/gpu/device/device_batched_gemm_softmax_gemm_permute_xdl_cshuffle.hpp
- include/ck/tensor_operation/gpu/grid/gridwise_batched_gemm_gemm_xdl_cshuffle_v1.hpp
- include/ck/tensor_operation/gpu/grid/gridwise_batched_gemm_softmax_gemm_xdl_cshuffle_v1.hpp
Fix for #370. Fix example; make padding on by default in example; fix argument checks
> Fix gemm-softmax-gemm-permute padding cases

- Dockerfile
- Jenkinsfile
- script/run_full_performance_tests.sh
These changes will allow us to use the same OS and ROCM versions (20.04 and 5.2.3) in our CI/QA as used by MIOpen and ONNX, while still being able to use the ck-9110 clang compiler as the default option.
> Upgrade the OS and ROCM versions.

- Config.cmake.in
The supported components name should match the name [here](https://github.com/ROCmSoftwarePlatform/composable_kernel/blob/01876afafe1c09028dc4d513b5d040cec798fae6/library/src/utility/CMakeLists.txt#L23).
This PR blocks https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1673
> Updated the supported components

- Jenkinsfile
- client_example/CMakeLists.txt
Two small changes in this PR:
1. Replace the obsolete offload-arch compiler flags with the new GPU_TARGETS macros. This should reduce the build times and size of resulting binaries by roughly 50%.
2. Fix a bug that causes a crash while building Client App.
> Replace the obsolete offload-arch flags with GPU_TARGETS and fix a bug.

- Dockerfile
- Jenkinsfile
- dev-requirements.txt
Several important changes:
1. Set the new default compiler (current latest version of branch amd-stg-open). This should fix all our compile and example errors.
2. Added a new build option to select a specific commit for compiler
3. Removed obsolete build option "Test Node", since now we can't run performance tests, bypassing all previous stages, since the ckProfiler is built in one of the first stages and then passed to the last stage
4. Moved the docker images from the amd repo to dockerhub. This should resolve connection issues and reduce push/pull times
5. Harmonized the dev-requirements.txt contents with MIOpen
> Fix build issues, set new compiler default, etc.

- script/process_perf_data.py
The python script processing the QA results was messing up the results for conv_bwd and gemm_bilinear kernels.
I have verified that the fix works correctly:
this is new row from the conv_bwd table:
'lwpck-474', 'hpe-sjc2-39', 'gfx90a', '104', '5.3.0', '5.3.22061-e8e78f1a', 'QA_release', '2022-10-26 07:05:44', '37.1707', '38.0164', '33.2186', '32.5096', '24.6142', '37.0726', '34.8511', '34.6174', '28.2624', '31.3456', '22.3235', '26.5103', '31.8428', '37.3862', '34.9756', '33.9038', '17.4158', '12.5944', '26.8995', '0', '93.6209', '119.044', '92.4938', '67.2132', '55.9901', '112.422', '104.379', '108.118', '72.628', '65.9462', '48.3366', '79.2362', '65.8616', '94.7894', '114.075', '110.304', '34.8068', '30.8174', '73.3233', '0', '88.0412', '112.222', '93.5699', '65.78', '57.061', …
> fix the script parsing the QA results

- library/src/tensor_operation_instance/gpu/grouped_conv3d_fwd/CMakeLists.txt
Internal user currently evaluating CK has met problems compiling as shared library. Diagnostic shows conv3d_fwd_instance is missing the -fPIC flag. 
```
ld.lld: error: relocation R_X86_64_32S cannot be used against symbol 'vtable for ck::tensor_operation::device::DeviceGroupedConvFwdMultipleD_Xdl_CShuffle<3, ck::tensor_layout::convolution::GNDHWC, ck::tensor_layout::convolution::GKZYXC, ck::Tuple<>, ck::tensor_layout::convolution::GNDHWK, unsigned short, unsigned short, float, unsigned short, ck::Tuple<>, unsigned short, ck::tensor_operation::element_wise::PassThrough, ck::tensor_operation::element_wise::PassThrough, ck::tensor_operation::element_wise::PassThrough, (ck::tensor_operation::device::ConvolutionForwardSpecialization)2, (ck::tensor_operation::device::GemmSpecialization)7, 1, …
```
> fix missing -fPIC flag for conv3d_fwd instance lib

- test/normalization/test_groupnorm_fp16.cpp
- test/normalization/test_groupnorm_fp32.cpp
We only need one test case here.
Because we already add the instances in the profiler.
> Remove redundant test in normalization

- test/CMakeLists.txt
GTest discovery works by querying test cases nested under test programs and exposing the test cases to ctest. As we are using GTest to write more granular test cases, disabling GTest discovery will make resulting test log much cleaner.
> Disable gtest discovery to run tests per-program not per-case

- Jenkinsfile
The CI got broken when someone created a branch "modified_half_function_in_math_v2.hpp".
As a result, github created some files named "modified_half_function_in_math_v2.hpp" that were subsequently scanned by the clang-format script. The script, obviously, didn't find c++ code in those files, and caused the CI builds to crash.
I have added a filter for the most common file extensions ".h", ".hpp" and ".cpp" that will ignore any such files in the .git folder.
> Fix CI error.

- include/ck/utility/math_v2.hpp
This P.R provides
Modified function of  `half_t __device__ abs(half_t x)` and `__device__ bool isnan(half_t x)` in `math_v2.hpp` to avoid some problems.
The old implementation of the two functions depends on implicit constructor to convert  `_Float16` (ck::half_t) to `struct __half`,  which seems be compiler-depending,  and caused issues while using device op classes directly from PyTorch environment
> modified functions for half_t in math_v2.hpp

- include/ck/tensor_operation/gpu/device/impl/device_batched_gemm_xdl.hpp
- include/ck/tensor_operation/gpu/device/impl/device_conv2d_bwd_data_xdl_nhwc_kyxc_nhwk.hpp
- include/ck/tensor_operation/gpu/device/impl/device_gemm_xdl.hpp
- include/ck/tensor_operation/gpu/device/impl/device_gemm_xdl_cshuffle.hpp
This is an additional check to catch the exception handled by asserts in develop mode when running a release build.
With this fix calls like "./bin/ckProfiler gemm 1 3 1 2 0 0 128 128 133 -1 -1 -1" will no longer produce wrong results and instead every kernel will issue an error message "does not support this problem".
I've also checked that other gemm sizes like 
"./bin/ckProfiler gemm 1 3 1 2 0 0 128 133 128 -1 -1 -1" 
or
"./bin/ckProfiler gemm 1 3 1 2 0 0 133 128 128 -1 -1 -1"
are also throwing the error. So no additional checks may be necessary.
> Make sure that GEMM sizes in K dimension are supported.

- include/ck/ck.hpp
- include/ck/tensor_operation/gpu/device/impl/device_batched_gemm_multiple_d_gemm_multiple_d_xdl_cshuffle.hpp
- include/ck/tensor_operation/gpu/device/impl/device_batched_gemm_reduce_xdl_cshuffle.hpp
- include/ck/tensor_operation/gpu/device/impl/device_batched_gemm_softmax_gemm_permute_xdl_cshuffle.hpp
- include/ck/tensor_operation/gpu/device/impl/device_batched_gemm_xdl.hpp
- include/ck/tensor_operation/gpu/device/impl/device_conv2d_backward_weight_xdl_c_shuffle_nhwc_kyxc_nhwk.hpp
- include/ck/tensor_operation/gpu/device/impl/device_conv2d_bwd_data_xdl_nhwc_kyxc_nhwk.hpp
- include/ck/tensor_operation/gpu/device/impl/device_conv2d_fwd_xdl_c_shuffle_bias_activation_add_nhwc_kyxc_nhwk.hpp
- include/ck/tensor_operation/gpu/device/impl/device_conv2d_fwd_xdl_c_shuffle_bias_activation_nhwc_kyxc_nhwk.hpp
- include/ck/tensor_operation/gpu/device/impl/device_conv2d_fwd_xdl_c_shuffle_nhwc_kyxc_nhwk.hpp
- include/ck/tensor_operation/gpu/device/impl/device_conv2d_fwd_xdl_nhwc_kyxc_nhwk.hpp
- include/ck/tensor_operation/gpu/device/impl/device_conv3d_fwd_xdl_ndhwc_kzyxc_ndhwk.hpp
- include/ck/tensor_operation/gpu/device/impl/device_convnd_bwd_data_nwc_kxc_nwk_dl.hpp
- include/ck/tensor_operation/gpu/device/impl/device_convnd_bwd_data_nwc_kxc_nwk_xdl.hpp
- include/ck/tensor_operation/gpu/device/impl/device_gemm_dl.hpp
- include/ck/tensor_operation/gpu/device/impl/device_gemm_reduce_xdl_cshuffle.hpp
- include/ck/tensor_operation/gpu/device/impl/device_gemm_xdl.hpp
- include/ck/tensor_operation/gpu/device/impl/device_gemm_xdl_cshuffle.hpp
- include/ck/tensor_operation/gpu/device/impl/device_gemm_xdl_layernorm_cshuffle.hpp
- include/ck/tensor_operation/gpu/device/impl/device_gemm_xdl_skip_b_lds.hpp
- include/ck/tensor_operation/gpu/device/impl/device_gemm_xdl_splitk_c_shuffle.hpp
- include/ck/tensor_operation/gpu/device/impl/device_grouped_gemm_xdl.hpp
We had about a dozen kernels that had some debug output, mostly commented out with "#if 0" conditions, but sometimes it was enabled and annoying some of the customers. 
I have introduced a DEBUG_LOG macro in ck.hpp header and tried to catch every instance of the output and disable it by default with the DEBUG_LOG set to 0.
> Add a flag to enable/disable debug output in many kernels.

- CHANGELOG.md
Please feel free to add more contents as needed.
In the future, every time you make a major commit, you should add a line about it in the changelog.md file.
> adding the first draft of changelog

- include/ck/tensor_operation/gpu/device/impl/device_elementwise_normalization_impl.hpp
- library/src/tensor_operation_instance/gpu/elementwise_normalization/device_elementwise_normalization_f16_instance.cpp
- test/elementwise_normalization/test_elementwise_layernorm_fp16.cpp
Due to request from customers, this kernel didn't work when N > 4096.
I have added instances for elementwise normalization to enable kernel when N is large (>4096 ). 
When M = 4096 and N =8192, bandwidth now  can reach 993.019GB/s.
Performance time can be 0.188849 ms
> Add instance for elementwise normlization

- test/batched_gemm_softmax_gemm_permute/test_batched_gemm_softmax_gemm_permute_bf16.cpp
Ran these tests on MI100 node as standalone and they also passed CI on MI100 node yesterday:
[----------] Global test environment tear-down
[==========] 26 tests from 3 test suites ran. (415679 ms total)
[  PASSED  ] 26 tests.
Previously the summary looked like this:
[----------] Global test environment tear-down
[==========] 20 tests from 3 test suites ran. (49917 ms total)
[  PASSED  ] 20 tests.
YOU HAVE 6 DISABLED TESTS
> enable batched_gemm_softmax_bf16 tests

- include/ck/ck.hpp
- include/ck/tensor_operation/gpu/grid/gridwise_batched_gemm_multiple_d_softmax_gemm_xdl_cshuffle_v1.hpp
- include/ck/tensor_operation/gpu/grid/gridwise_batched_gemm_softmax_gemm_xdl_cshuffle_v1.hpp
We had to introduce some workarounds for some of our tests to pass on MI100 a few months ago.
Looks like the issues that caused that failure have been fixed in our latest compiler version.
> Remove the workaround for bf16 attention tests.

- include/ck/utility/array_multi_index.hpp
- include/ck/utility/multi_index.hpp
- include/ck/utility/statically_indexed_array_multi_index.hpp
PyTorch hipify does not support circular includes. Remove circular includes from relevant header files.
> Remove circular includes

- Jenkinsfile
This change will build and archive deb packages for tests and ckProfiler during the daily QA runs with develop branch and default compiler.
> Build and archive deb packages.

- include/ck/tensor_operation/gpu/device/impl/device_contraction_multiple_d_xdl_cshuffle.hpp
- script/cmake-ck-dev.sh
- Disable tensor contraction fp64 on MI100, which does not support mfma f64
> disable tensor contraction f64 on MI100

- Jenkinsfile
- cmake/EnableCompilerWarnings.cmake
One of the recent changes has triggered a "reserved-identifier" warning that currently can't be eliminated by any means other then just getting suppressed. Also, we need to start catching any new warnings during the CI process, so I've enabled the -Werror and BUILD_DEV=ON compiler options.
> Suppress reserved-identifier warning and catch all warnings.

- CHANGELOG.md
- Jenkinsfile
- example/01_gemm/CMakeLists.txt
- example/02_gemm_bilinear/CMakeLists.txt
- example/29_batched_gemm_bias_e_permute/CMakeLists.txt
- example/30_grouped_conv_fwd_multiple_d/CMakeLists.txt
- include/ck/ck.hpp
- include/ck/tensor_operation/gpu/device/impl/device_batched_contraction_multiple_d_wmma_cshuffle.hpp
- include/ck/tensor_operation/gpu/device/impl/device_gemm_multiple_d_wmma_cshuffle.hpp
- include/ck/tensor_operation/gpu/device/impl/device_gemm_wmma.hpp
- include/ck/tensor_operation/gpu/device/impl/device_grouped_conv_fwd_multiple_d_wmma_cshuffle.hpp
- include/ck/tensor_operation/gpu/grid/gridwise_gemm_multiple_d_wmma_cshuffle.hpp
- include/ck/tensor_operation/gpu/grid/gridwise_gemm_wmma.hpp
Added the necessary flags for the gfx1101 and gfx1102. 
Also, modified Jenkinsfile to build for those targets correctly, replacing the GPU_TARGETS with CXX_FLAGS.
> [gfx110x] support Navi3x architectures.

- include/ck/utility/amd_buffer_addressing.hpp
Currently OOB use `0x7fff ffff` as an offset when address is not valid, intended to manually set the address out-of-bound. But that is not a dword-aligned address, and can potentially result in GPU crash (for buffer atomic)
change to `0x8000 0000` to have a aligned address
> fix a bug with non-dword-aligned offset when OOB, in case crash

- include/ck/tensor_operation/gpu/device/impl/device_gemm_xdl.hpp
According to issue https://github.com/ROCmSoftwarePlatform/composable_kernel/issues/622, remove debug asserts.
> Fix debug build crash due to c assert

- include/ck/tensor_operation/gpu/device/impl/device_grouped_conv_fwd_multiple_d_wmma_cshuffle.hpp
While trying to make strings returned by GetTypeString unique, I've appended some XDL parameters to the name of some WMMA kernel. For some reason, local builds and our CI didn't see any problem with it, but the MIOpen CI reports errors. So I'm going to clean up that string name.
> Get rid of XDL parameters in WMMA kernel string.

- test/grouped_convnd_bwd_weight/grouped_convnd_bwd_weight.cpp
Since the weight value is highly dependent both on `group` & `batch` of the input/output tensors. I decided to further reduce them & limit the maximum weight value just below 1500.
After this PR, no errors were found on my MI250 machine by 200 runs. I believe this PR is good enough to avoid failure test.
> Fix the test 'TestGroupedConvndBwdWeight'

- CMakeLists.txt
- example/30_grouped_conv_fwd_multiple_d/run_grouped_conv_fwd_bias_relu_add_wmma_example.inc
- include/ck/tensor_operation/gpu/grid/gridwise_gemm_multiple_d_wmma_cshuffle.hpp
A bug found on develop, shared memory allocation not consider the shuffle C matrix part.
> [Navi3x] Fix Gridwise_multiple_d operation

- CMakeLists.txt
- script/cmake-ck-dev.sh
To make navi3x only performance optimize compile option into a CMake Option "USE_OPT_NAVI3X"
- `-mcumode`, the option to limit the LDS access scope of each CU to its own part, access to another part of LDS in same WGP is not allowed. That option give a lot performance gain if kernel code use LDS.
- `-mno-wavefrontsize64`, the option to ask the GPU run in wave32 mode, the primitive thread group of GPU composed of 32 threads (Native support of Navi Series silicon) instead of 64 (Native support of MI Series silicon).
> Add CMake Option "USE_OPT_NAVI3X"
